like(1)
shinonome-inc/backend-final-assignment-taman pull request #10
Opened 2023-07-02 03:44 UTC by TamanPG

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-07-02 09:54 UTC, Shiota620 requested changes
レビューしました。
ご確認よろしくお願い致します。

2023-07-02 09:54 UTC, Shiota620 commented on tweets/views.py
> +        context["liked_count"] = Like.objects.filter(target_id=self.kwargs["pk"]).count()
HOME画面から目のマークを押したときにN+1問題が発生しています。

2023-07-03 07:54 UTC, TamanPG commented on tweets/views.py
> +    queryset = model.objects.select_related("user").prefetch_related("likes").order_by("-created_at")
修正しました。

2023-07-03 07:54 UTC, TamanPG commented on accounts/views.py
> +        tweets = Tweet.objects.select_related("user").prefetch_related("likes").filter(user=user)
修正しました。

2023-07-03 08:02 UTC, TamanPG commented on tweets/admin.py
> +admin.site.register(Like)
修正しました。

2023-07-03 08:06 UTC, TamanPG commented on tweets/views.py
> +        context["liked_count"] = Like.objects.filter(target_id=self.kwargs["pk"]).count()
自分ではN+1は確認できなかったのですが、どのような状況で(またはどのクエリで)発生したのでしょうか。
自分が見逃しているかもしれませんので、ご教授いただければ幸いです。
また、原因と考えられる部分を修正しました。

2023-07-03 08:07 UTC, TamanPG commented on tweets/models.py
> +class Like(models.Model):
修正しました。

2023-07-03 08:07 UTC, TamanPG commented on templates/tweets/like.html
> +    <span id="count_{{tweet.id}}">{{ tweet.likes.count }}</span>
修正しました。

2023-07-03 14:20 UTC, Shiota620 reviewed
一次レビューはこれで終了です。お疲れさまでした。

TAK848さん二次レビューよろしくお願い致します。

2023-07-08 15:25 UTC, TAK848 reviewed
ほぼコメント不要なくらいよくかけています。
数点1通り確認いただけると！

2023-07-08 15:25 UTC, TAK848 commented on templates/tweets/like.html
> +    {% if is_liked is True or tweet.id in user_like_list %}
絶対NGな`== True`形式ではない（[参考，flake8のE712](https://www.flake8rules.com/rules/E712.html)）ので良いですが，`is True`はis is trueと冗長で，個人的には無くても良いとは思いますが，どうでしょう？（任意）

2023-07-08 15:25 UTC, TAK848 commented on tweets/models.py
> +    target = models.ForeignKey(Tweet, related_name="likes", on_delete=models.CASCADE)
`related_name="likes"` 👍

2023-07-08 15:25 UTC, TAK848 commented on tweets/views.py
> +
existsのチェックせずとも，deleteは可能です！SQLクエリの回数削減にもつながります

使う必要は今回無いですが，delete関数の返り値にdictが返ってきて，削除個数などが取得できます
https://docs.djangoproject.com/en/4.2/ref/models/querysets/#delete

2023-07-09 01:46 UTC, TamanPG commented on templates/tweets/like.html
> +    {% if is_liked is True or tweet.id in user_like_list %}
確かにそうですね! 修正しました。

2023-07-09 01:46 UTC, TamanPG commented on tweets/views.py
> +
了解です。修正しました。

2023-07-09 06:31 UTC, TAK848 approved these changes

2023-07-09 06:33 UTC, merged