Feature/signup
shinonome-inc/backend-final-assignment-taman pull request #2
Opened 2023-05-07 06:14 UTC by TamanPG

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-05-08 15:17 UTC, JunyaMakita commented
LGMT

2023-05-10 03:30 UTC, Akinori13 requested changes
とてもよく書けています！ほんの少しだけコメントしました！

2023-05-10 03:30 UTC, Akinori13 commented on accounts/views.py
>  # from django.shortcuts import render
不要な行は削除しちゃいましょう！

2023-05-10 03:30 UTC, Akinori13 commented on tweets/views.py
>  # from django.shortcuts import render
ここも

2023-05-10 13:15 UTC, merged