Feature/login logout
shinonome-inc/backend-final-assignment-taman pull request #6
Opened 2023-05-14 06:09 UTC by TamanPG

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-05-15 02:37 UTC, gw31415 commented
いい感じだと思います！
コンフリクトしているようなのでその解消だけお願いします！

2023-05-15 02:41 UTC, gw31415 commented on accounts/tests.py
> +        valid_data = {
`self.user` 中の値を参照してもいいかなと思いましたが、この程度なら好みの問題だと思うのでコメントに留めておきます。

2023-05-15 06:06 UTC, TamanPG commented on accounts/tests.py
> +        valid_data = {
コメント・レビューありがとうございます！

2023-05-19 04:28 UTC, gaato commented on accounts/views.py
> +    model = User
`/accounts/{username}/` にアクセスするとエラーが出ます．（ちゃんとブラウザでテストしてね）
このファイルのどこかで凡ミスしているので探してみてください．

もしかしたらエラーを読むのに慣れていないと見つけづらいミスかもしれないのでどうしても分からなかったら聞いてください．

2023-05-19 04:35 UTC, masaya09 requested changes

2023-05-19 04:35 UTC, masaya09 commented on accounts/tests.py
> +        response = self.client.get(self.url)
logoutは確かにgetでも可能ですが、django5.0から非推奨になることもあってpostでの実行おねがいします。

[公式ドキュメントでの記載](https://docs.djangoproject.com/en/4.1/releases/4.1/#log-out-via-get)

[実際のLogoutViewのコード](https://github.com/django/django/blob/main/django/contrib/auth/views.py#L124)では、http_methodを見てわかる通りgetはできないようになっています。

2023-05-19 04:35 UTC, masaya09 commented on accounts/views.py
> +    pass
これ別に使用してないので削除でOKです。

[ 詳細 ] 
現状urlsから呼び出してるLogin, Logoutはurls.pyで記載している`from django.contrib.auth import views as auth_views`からimportしてますので、ここで記載してるものではないです。

2023-05-19 04:35 UTC, masaya09 commented on templates/accounts/profile.html
> +{% block title %}Profile{% endblock %}
ここの記述をbase.htmlに記述しなかった理由はありますか？

2023-05-19 04:35 UTC, masaya09 commented on templates/accounts/login.html
> +<link rel="stylesheet" href="{% static 'css/twitterclone.css' %}">
ここも同様

2023-05-19 04:35 UTC, masaya09 commented on accounts/tests.py
> +#    def test_success_get(self):
class TestUserProfileView(TestCase)のテストも記述お願いします

2023-05-19 05:59 UTC, TamanPG commented on templates/accounts/profile.html
> +{% block title %}Profile{% endblock %}
すみません消し忘れです
記述はbase.htmlにあります

2023-05-21 14:57 UTC, gaato commented
LGTM！

2023-05-21 14:57 UTC, merged