Feature/tweet
shinonome-inc/backend-final-assignment-taman pull request #8
Opened 2023-06-04 04:57 UTC by TamanPG

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-06-04 08:26 UTC, YukiY727 commented on mysite/settings.py
> +        return False
ここをFalseにしている理由はどのようなものでしょうか？
こちら、Falseのままだと、toolbarが出ないと思うのですが、、、

2023-06-05 01:22 UTC, TamanPG commented on mysite/settings.py
> +        return False
テスト実行時やpush時にTrueにしておくとテストが通らなくなってしまうのでFalseにしてあります(動作確認時はTrueにしてます)。
こちらの資料に従ってます→https://shinonome-inc.notion.site/SQL-N-1-django-debug-toolbar-26315565b11d491fb21078f1883710aa

2023-06-05 05:13 UTC, TamanPG commented on mysite/settings.py
> +        return False
SQL_DEBUGをFalseにしようとして間違えたのがそのままでした。修正しました。

2023-06-06 02:46 UTC, YukiY727 commented on mysite/settings.py
> +        return False
OKです！

2023-06-06 02:47 UTC, YukiY727 approved these changes

2023-06-07 04:50 UTC, Akinori13 requested changes
良い感じです！少しだけコメントしました！

2023-06-07 05:57 UTC, TamanPG commented on tweets/views.py
> +        return self.render_to_response(context)
これが無いとSQLで2 duplicatesが発生するので加えましたが、必ず必要ではありません(参照記事https://shinonome-inc.notion.site/14cadc160a1e4c749f24ce9c0dd3e269?v=ae59ff8f1e7948a2a3a5103d03336b7c&p=26315565b11d491fb21078f1883710aa&pm=s)。
もし無い方が良いということでしたら修正します。

2023-06-07 06:00 UTC, Akinori13 commented on tweets/views.py
> +        return self.render_to_response(context)
確かにそうですね！修正しなくて大丈夫です！

2023-06-07 06:05 UTC, TamanPG commented on templates/base.html
> +          {{ request.user }}
修正しました。

2023-06-07 06:06 UTC, TamanPG commented on accounts/static/css/twitterclone.css
> +    margin: 5px 0;
修正しました。

2023-06-07 06:06 UTC, TamanPG commented on tweets/models.py
> -# class Tweet(models.Model):
8行目にcreated_atフィールドは設けてあるのですが、それとはまた別のものでしょうか？

2023-06-07 06:44 UTC, Akinori13 commented on accounts/tests.py
>          self.assertTemplateUsed(response, "accounts/profile.html")
①ログインのプロフィールよりも別のユーザーのプロフィール画面にGETしましょう。
②ログインユーザーで1つ、プロフィール画面でアクセスするユーザーのツイートを2つ作成して、テストしましょう。

2023-06-07 06:44 UTC, Akinori13 commented on tweets/models.py
> -# class Tweet(models.Model):
見落としました！大丈夫です！

2023-06-07 10:22 UTC, TamanPG commented on accounts/tests.py
>          self.assertTemplateUsed(response, "accounts/profile.html")
修正しました。

2023-06-08 04:05 UTC, Akinori13 commented
LGTM

2023-06-08 04:05 UTC, merged