Feature/follow unfollow
shinonome-inc/backend-final-assignment-taman pull request #9
Opened 2023-06-18 07:49 UTC by TamanPG

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-06-21 13:51 UTC, gaato requested changes
見た目を含め細かいところにもにも気を配れていて good です！
細かいですが１点だけコメントしました．

2023-06-22 13:23 UTC, TamanPG commented on accounts/views.py
> +            return HttpResponseBadRequest(render(request, "error/400.html"))
該当箇所の修正+リダイレクト先の統一を行いました。

2023-06-23 10:45 UTC, gaato requested changes

2023-06-23 10:45 UTC, gaato commented on accounts/views.py
> +            return HttpResponseBadRequest(redirect_url)
指示が分かりづらくて申し訳ないです．
**フォロー済みのパターンに限っては**普通に使っていても起こりうるので 400 (Bad Request) ではなく正常の動作（home または profile にリダイレクト）で良いのではないか？（つまり「異常」ではなく「正常」と扱う）という指摘であって，全ての例外についてメッセージ付きでプロフィールにリダイレクトさせてほしかったわけではないです．

また，ブラウザで確認してもらえば分かると思うのですがこれはリダイレクトにはなっておらず，ただ `redirect_url` の中身が表示されるだけになっています．
![image](https://github.com/shinonome-inc/backend-final-assignment-taman/assets/57865205/818d1186-a0f9-4360-87bb-1cf15ca19235)

他の場所も同様ですが，`400.html` を表示する実装はとても良いと思ったので他の場所はさっきの状態で大丈夫です．`git revert` などを使って戻してから修正すると良いと思います．

2023-06-23 22:39 UTC, TamanPG commented on accounts/views.py
> +            return HttpResponseBadRequest(redirect_url)
テスト項目には400エラーと書いてあるのですが、この場合に限っては302→200の普通のリダイレクトで良いということでしょうか？

2023-06-26 05:42 UTC, gaato commented on accounts/views.py
> +            return HttpResponseBadRequest(redirect_url)
そうです！

2023-06-26 05:53 UTC, gaato approved these changes
LGTM!

2023-06-26 05:53 UTC, merged